name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  workflow_dispatch: # Allows you to manually trigger the deployment from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required for the action to push to the gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Node 18 is compatible with Angular 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Angular Project
        run: npx ng build --configuration production --base-href /form-builder/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/form-builder
          publish_branch: gh-pages
